CREATE TABLE [dbo].[Paciente] (
    [Id_paciente]                         INT          IDENTITY (1, 1) NOT NULL,
    [Nome]                                VARCHAR (50) NULL,
    [Apelido]                             VARCHAR (50) NULL,
    [Nacionalidade]                       VARCHAR (50) NULL,
    [Data_nascimento]                     VARCHAR (50) NULL,
    [Sexo]                               VARCHAR (50) NULL,
    [CPF ]                                VARCHAR (50) NULL,
    [RG ]                                 VARCHAR (50) NULL,
    [Cidade ]                             VARCHAR (50) NULL,
    [Cidade_Natal ]                       VARCHAR (50) NULL,
    [Endereco ]                           VARCHAR (50) NULL,
    [Bairro ]                             VARCHAR (50) NULL,
    [Complemento ]                        VARCHAR (50) NULL,
    [Numero ]                             VARCHAR (50) NULL,
    [CEP ]                                VARCHAR (50) NULL,
    [Telefone ]                           VARCHAR (50) NULL,
    [Telefone_celular ]                   VARCHAR (50) NULL,
    [E_mail ]                             VARCHAR (50) NULL,
    [Nome_da_Mae ]                        VARCHAR (50) NULL,
    [Nome_do_Pai ]                        VARCHAR (50) NULL,
    [Telefone_contato ]                   VARCHAR (50) NULL,
    [Estado_Civil ]                       VARCHAR (50) NULL,
    [Orgao_expedicao ]                    VARCHAR (50) NULL,
    [data_expedicao ]                     VARCHAR (50) NULL,
    [pais ]                               VARCHAR (50) NULL,
    [referencia_familiar ]                VARCHAR (50) NULL,
    [UF ]                                 VARCHAR (2)  NULL,
    [UF_Naturalidade]                     VARCHAR (2)  NULL,
    [UF_Contato ]                         VARCHAR (2)  NULL,
    [Observacao_pessoal ]                 VARCHAR (50) NULL,
    [Febre_Amarela1 ]                     VARCHAR (50) NULL,
    [Febre_Amarela2 ]                     VARCHAR (50) NULL,
    [Febre_Amarela3]                      VARCHAR (50) NULL,
    [Febre_Amarela_Unica]                 VARCHAR (50) NULL,
    [HepatiteB_1 ]                        VARCHAR (50) NULL,
    [HepatiteB_2 ]                        VARCHAR (50) NULL,
    [HepatiteB_3 ]                        VARCHAR (50) NULL,
    [HepatiteB_Unica ]                    VARCHAR (50) NULL,
    [Influenza_1 ]                        VARCHAR (50) NULL,
    [Influenza_2 ]                        VARCHAR (50) NULL,
    [Influenza_3 ]                        VARCHAR (50) NULL,
    [Influenza_Unica ]                    VARCHAR (50) NULL,
    [Poliomelite_1 ]                      VARCHAR (50) NULL,
    [Poliomelite_2 ]                      VARCHAR (50) NULL,
    [Poliomelite_3 ]                      VARCHAR (50) NULL,
    [Poliomelite_Unica ]                  VARCHAR (50) NULL,
    [Pneumococica_10-Valente_1 ]          VARCHAR (50) NULL,
    [Pneumococica_10-Valente_2 ]          VARCHAR (50) NULL,
    [Pneumococica_10-Valente_3 ]          VARCHAR (50) NULL,
    [Pneumococica_10-Valente_Unica ]      VARCHAR (50) NULL,
    [Pneumococica_23-Valente_1 ]          VARCHAR (50) NULL,
    [Pneumococica_23-Valente_2 ]          VARCHAR (50) NULL,
    [Pneumococica_23-Valente_3 ]          VARCHAR (50) NULL,
    [Pneumococica_23-Valente_Unica ]      VARCHAR (50) NULL,
    [Tetraviral_1 ]                       VARCHAR (50) NULL,
    [Tetraviral_2 ]                       VARCHAR (50) NULL,
    [Tetraviral_3 ]                       VARCHAR (50) NULL,
    [Tetraviral_Unica ]                   VARCHAR (50) NULL,
    [Triplice_Bacteriana_1 ]              VARCHAR (50) NULL,
    [Triplice_Bacteriana_2 ]              VARCHAR (50) NULL,
    [Triplice_Bacteriana_3 ]              VARCHAR (50) NULL,
    [Triplice_Bacteriana_Unica ]          VARCHAR (50) NULL,
    [Triplice_Viral_1 ]                   VARCHAR (50) NULL,
    [Triplice_Viral_2 ]                   VARCHAR (50) NULL,
    [Triplice_Viral_3 ]                   VARCHAR (50) NULL,
    [Triplice_Viral_Unica ]               VARCHAR (50) NULL,
    [Vacina_DT(difteria_e_tetano)_1 ]     VARCHAR (50) NULL,
    [Vacina_DT(difteria_e_tetano)_2 ]     VARCHAR (50) NULL,
    [Vacina_DT(difteria_e_tetano)_3 ]     VARCHAR (50) NULL,
    [Vacina_DT(difteria_e_tetano)_Unica ] VARCHAR (50) NULL,
    [Vacina_Menigocica_C_1 ]              VARCHAR (50) NULL,
    [Vacina_Menigocica_C_2 ]              VARCHAR (50) NULL,
    [Vacina_Menigocica_C_3 ]              VARCHAR (50) NULL,
    [Vacina_Menigocica_C_Unica ]          VARCHAR (50) NULL,
    [Vacina_Oral_Rotavirus_Humano_1 ]     VARCHAR (50) NULL,
    [Vacina_Oral_Rotavirus_Humano_2 ]     VARCHAR (50) NULL,
    [Vacina_Oral_Rotavirus_Humano_3 ]     VARCHAR (50) NULL,
    [Vacina_Oral_Rotavirus_Humano_Unica ] VARCHAR (50) NULL,
    [SOC_ESCOLARIDADE ]                   VARCHAR (50) NULL,
    [SOC_ESTUDO ]                         INT          NULL,
    [SOC_FEZCURSO ]                       VARCHAR (50) NULL,
    [SOC_CURSO ]                          VARCHAR (50) NULL,
    [SOC_TRABALHO ]                       VARCHAR (50) NULL,
    [SOC_PROFISSÃO ]                      VARCHAR (50) NULL,
    [SOC_FILHOS ]                         VARCHAR (50) NULL,
    [SOC_RESPONSAVEL ]                    VARCHAR (50) NULL,
    [SOC_RUA ]                            VARCHAR (50) NULL,
    [SOC_TEMPO ]                          VARCHAR (50) NULL,
    [SOC_INSTITUICAO ]                    VARCHAR (50) NULL,
    [SOC_NOMEINSTITUICAO]                 VARCHAR (50) NULL,
    [SOC_FAMILIAR ]                       VARCHAR (50) NULL,
    [SOC_PARENTESCO ]                     VARCHAR (50) NULL,
    [SOC_ADICIONAIS ]                     VARCHAR (50) NULL,
    [PAT_FUMANTE ]                        VARCHAR (50) NULL,
    [PAT_ALERGIA ]                        VARCHAR (50) NULL,
    [PAT_ALCOOL ]                         VARCHAR (50) NULL,
    [PAT_REMEDIO ]                        VARCHAR (50) NULL,
    [PAT_DROGA ]                          VARCHAR (50) NULL,
    [PAT_DIABETES ]                       VARCHAR (50) NULL,
    [PAT_COLESTEROL ]                     VARCHAR (50) NULL,
    [PAT_CARDIACO ]                       VARCHAR (50) NULL,
    [PAT_AVC ]                            VARCHAR (50) NULL,
    [PAT_RINS ]                           VARCHAR (50) NULL,
    [PAT_RESPIRATORIO ]                   VARCHAR (50) NULL,
    [PAT_INTERNACAO]                      VARCHAR (50) NULL,
    [PAT_CANCER ]                         VARCHAR (50) NULL,
    [PAT_HEREDITARIA ]                    VARCHAR (50) NULL,
    [PAT_DEFICIENCIA ]                    VARCHAR (50) NULL,
    [PAT_HEPATITE ]                       VARCHAR (50) NULL,
    [PAT_DST ]                            VARCHAR (50) NULL,
    [PAT_TEMPO_F ]                        VARCHAR (50) NULL,
    [PAT_QUAL_A ]                         VARCHAR (50) NULL,
    [PAT_TEMPO_AL ]                       VARCHAR (50) NULL,
    [PAT_QUAL_R ]                         VARCHAR (50) NULL,
    [PAT_QUAL_D ]                         VARCHAR (50) NULL,
    [PAT_QUAL_DI ]                        VARCHAR (50) NULL,
    [PAT_QUANTO_CO ]                      VARCHAR (50) NULL,
    [PAT_QUAL_CAR ]                       VARCHAR (50) NULL,
    [PAT_QUANDO_AVC ]                     VARCHAR (50) NULL,
    [PAT_TIPO_RIN ]                       VARCHAR (50) NULL,
    [PAT_QUAL_RES ]                       VARCHAR (50) NULL,
    [PAT_POR_IN ]                         VARCHAR (50) NULL,
    [PAT_QUAL_CA ]                        VARCHAR (50) NULL,
    [PAT_QUAL_HE ]                        VARCHAR (50) NULL,
    [PAT_QUAL_DE ]                        VARCHAR (50) NULL,
    [PAT_QUAL_HEP ]                       VARCHAR (50) NULL,
    [PAT_QUAL_DST ]                       VARCHAR (50) NULL,
    [Nome_medico ]                        VARCHAR (50) NULL,
    [PAT_motivo ]                         VARCHAR (50) NULL,
    [PAT_local_tratamento ]               VARCHAR (50) NULL,
    [PAT_intervercoes_cirurgica ]         VARCHAR (50) NULL,
    [PAT_observacao ]                     VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([Id_paciente] ASC)
);

